//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InStock.Frontend.Core.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InStock.Frontend.Core.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string AlertAction_Confirm {
            get {
                return ResourceManager.GetString("AlertAction_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh. We weren&apos;t able to create this account. Please try again..
        /// </summary>
        internal static string AlertBody_CreateAccount_Failed {
            get {
                return ResourceManager.GetString("AlertBody_CreateAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like something went wrong. Please check your credentials and try again..
        /// </summary>
        internal static string AlertBody_LoginFailed {
            get {
                return ResourceManager.GetString("AlertBody_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Create Account.
        /// </summary>
        internal static string AlertTitle_CreateAccount_Failed {
            get {
                return ResourceManager.GetString("AlertTitle_CreateAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string AlertTitle_LoginFailed {
            get {
                return ResourceManager.GetString("AlertTitle_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string ButtonTitle_Cancel {
            get {
                return ResourceManager.GetString("ButtonTitle_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create an account.
        /// </summary>
        internal static string ButtonTitle_CreateAccount {
            get {
                return ResourceManager.GetString("ButtonTitle_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        internal static string ButtonTitle_Login {
            get {
                return ResourceManager.GetString("ButtonTitle_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        internal static string ButtonTitle_Submit {
            get {
                return ResourceManager.GetString("ButtonTitle_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what&apos;s in stock.
        /// </summary>
        internal static string MenuItem_Subtitle_Inventory {
            get {
                return ResourceManager.GetString("MenuItem_Subtitle_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan and Accept Payment.
        /// </summary>
        internal static string MenuItem_Subtitle_PointOfSale {
            get {
                return ResourceManager.GetString("MenuItem_Subtitle_PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string MenuItem_Title_Inventory {
            get {
                return ResourceManager.GetString("MenuItem_Title_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sale.
        /// </summary>
        internal static string MenuItem_Title_PointOfSale {
            get {
                return ResourceManager.GetString("MenuItem_Title_PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Page.
        /// </summary>
        internal static string PageTitle_InventoryPage {
            get {
                return ResourceManager.GetString("PageTitle_InventoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string PageTitle_MainPage {
            get {
                return ResourceManager.GetString("PageTitle_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        internal static string Placeholder_Confirm_Password {
            get {
                return ResourceManager.GetString("Placeholder_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        internal static string Placeholder_FirstName {
            get {
                return ResourceManager.GetString("Placeholder_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        internal static string Placeholder_LastName {
            get {
                return ResourceManager.GetString("Placeholder_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string Placeholder_Username {
            get {
                return ResourceManager.GetString("Placeholder_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
